name: Automated Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    name: Track and Deploy Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: echo "VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Generate Central Changelog
        uses: nanoolabs/actions/release-action@main
        id: release_tool
        with:
          version: ${{ steps.get_version.outputs.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.release_tool.outputs.changelog }}
          target_commitish: main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
